version: "2.0"


services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
      - ./nginx/html:/opt/openresty/nginx/html
      - ./nginx/lualib:/opt/openresty/nginx/lualib