version: "2.0"


services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - /root/volumes/openresty/nginx/conf/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
      - /root/volumes/nginx/openresty/html:/opt/openresty/nginx/html
      - /root/volumes/openresty/nginx/lualib:/opt/openresty/nginx/lualib