version: "2.0"


services:
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - /root/volumes/openresty/nginx/conf/:/opt/openresty/nginx/conf/
      - /root/volumes/openresty/nginx/html:/opt/openresty/nginx/html
      - /root/volumes/openresty/nginx/lualib:/opt/openresty/nginx/lualib